### ISSUE TITLE
Casos de Uso: El caso de uso se ostenta aqui

### ISSUE THREAD

**Issue by vmcabreu** [alexey1254/proyecto-ets#23]
El link debe de redireccionar a la imagen del DIagrama de Casos de Uso

**Comment by GraceCaraballoP** [comment]
El enlace debe llevar a la descripción y ya consta en el enlace

**Comment by vmcabreu** [comment]
Debe de llevar a la descripción del proyecto del idioma en el cual se esta viendo el caso de uso,
ES_Caso de Uso ----> ES_Home
